#!/bin/bash

bin_num=${BINARY}
dec_num=0
base=1
length=${#bin_num}

for (( i=$length-1; i>=0; i-- ))
do
  digit=${bin_num:$i:1}
  if [ "$digit" -eq 1 ]; then
    dec_num=$((dec_num + base))
  fi

  base=$((base * 2))
done

echo $dec_num
