#!/usr/bin/env bash

# This script configures an Nginx server to include a 301 redirect for /redirect_me using rewrite

# Update the package list
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Ensure Nginx is running
sudo service nginx start

# Add a 301 redirect configuration using rewrite in the Nginx default site
sudo sed -i "/server_name _;/a \\
    rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

