#!/usr/bin/env bash
# This script configures an Nginx server to include a 301 redirect for /redirect_me using a location block

# Update the package list
apt-get update -y

# Install Nginx
apt-get install nginx -y

# Ensure Nginx is running
service nginx start

# Add the location block below server_name
sed -i "/server_name _;/a \\
    location = /redirect_me {\\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\
    }" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
