#!/usr/bin/env bash
# This script configures an Nginx server to include a 301 redirect for both /redirect_me and /redirect_me/

# Update the package list
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Ensure Nginx is running
service nginx start

# Add the location block to handle both /redirect_me and /redirect_me/
sudo sed -i "/server_name _;/a \
    location ~^/redirect_me(/?)$ {\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
    }" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

