#!/usr/bin/env bash
# Configures Nginx to listen on port 80 and ensures it's running.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i 's/listen [::]:80 default_server;/listen 0.0.0.0:80 default_server;/' /etc/nginx/sites-available/default
nginx -t && service nginx restart
curl -I http://0:80
