#!/usr/bin/env bash
# This script displays a list of currently running processes for all users,
# including processes without a TTY, in a user-oriented format with process hierarchy.

ps -eH -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command
