#!/usr/bin/env bash
# This script manages the 'manage_my_process' process

PROCESS_SCRIPT="./manage_my_process"
PID_FILE="/var/run/my_process.pid"

start_process() {
	nohup "$PROCESS_SCRIPT" &> /dev/null &
	echo $! > "$PID_FILE"
  echo "manage_my_process started"
}

stop_process() {
	kill "$(cat "$PID_FILE")" && rm -f "$PID_FILE"
	echo "manage_my_process stopped"
}

restart_process() {
    stop_process
    start_process
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
