#!/usr/bin/env bash
#script stops the 4-to_infinity_and_beyond process without using killall.

# Find the PID of the 4-to_infinity_and_beyond process
PID=$(pgrep -f "7-highlander")

if [ -n "$PID" ]; then
	# Send the SIGTERM signal by writing to /proc/[PID]/task/[PID]/sig_stop
	kill -s SIGINT "$PID"
fi
