#!/usr/bin/env bash
# This script tells a story based on the content of the /etc/passwd file.
# Read the /etc/passwd file line by line

while IFS=: read -r username _ userid _ homedir _; do
    # Print the formatted story
    echo "The user $username is part of the $userid gang, lives in $homedir and rides ${SHELL}. $userid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
